### ISSUE TITLE
Free draw tool naming

### ISSUE THREAD

**Issue by Hero-Solutions** [annotorious/annotorious-v2-selector-pack#3]
I'm currently working out a free drawing tool, but I'm unsure what to call it. For my current work in progress, I'll call it "freedrawing", with class names such as "EditableFreeDrawing". Please let me know if you think this should be called differently.

**Comment by rsimon** [comment]
I think folks mostly refer to it as 'freehand' drawing? So maybe 'Freehand', 'EditableFreehand', 'Freehand(Drawing)Tool' or something like that?

**Comment by Hero-Solutions** [comment]
You got it!

**Comment by Hero-Solutions** [comment]
The freehand drawing tool has been added in #4. Feel free to provide feedback for improvements.

**Comment by rsimon** [comment]
The freehand drawing tool is supercool (especially in touch mode!)

> Feel free to provide feedback for improvements.

The only minor thing I noticed: it does allow you to create zero-length annotations, with a singe click. That also means that I'm always creating a zero-length annotation unintentionally, before I can select an existing annotations. 

You could check the length of the path in [onMouseUp](https://github.com/recogito/annotorious-selector-pack/blob/main/src/freehand/RubberbandFreehandTool.js#L42-L44) and then fire a cancel event instead of creating the selection, in the same way as e.g. the [rectangle tool does](https://github.com/recogito/annotorious/blob/main/src/tools/rectangle/RubberbandRectTool.js#L45-L54).

**Comment by Hero-Solutions** [comment]
Good point, I'll fix that asap. Thanks for reviewing and merging it!

I'm currently also thinking of making a very similar freehand drawing tool that allows you to draw multiple disconnected drawings, but I'm unsure what mechanism to use to make it stop drawing. For the current freehand tool, I figured it would be most user-friendly to make it stop drawing on mouseUp, but this wouldn't work with multiple disconnected drawings.
I'm also not sure if I can integrate this functionality somehow into the existing tool (and provide a way to configure it as such - although I don't know how yet), or if I should make a new tool instead.

**Comment by Hero-Solutions** [comment]
Fixed in #5. Feel free to provide feedback if you think this needs any changing.

**Comment by rsimon** [comment]
It's great! I published releases for Annotorious and AnnotoriousOSD with all your latest changes + I published the plugin to npm & added some minimal documentation. (So far only for Annotorious standard version and `<script>` import.)
